FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p data

COPY app.py db.py logger.py ./
COPY data/file_io.py data/__init__.py ./data/

EXPOSE 5000

CMD ["python", "app.py"]